# Site settings
title: Chang Min Park
description: 'Senior Software Engineer at Yahoo!'
url: 'https://changminpark.github.io'
baseurl: ''
google_analytics: 'UA-206787238-1'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Chang Min Park'
  email: pcm4150@gmail.com
  #  twitter_username: joshgerdes
  #  facebook_username: joshgerdes
  medium_id: pcm4150
  google_scholar_id:  OvD8H00AAAAJ
  github_username:  ChangMinPark
  linkedin_username:  changmpark

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
# permalink: /:year/:title/
permalink: /:title
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
